### ISSUE TITLE
CurrencyExchange project Target Framework

### ISSUE THREAD

**Issue by jaszb** [scottaddie/ContosoLending#1]
Hi Scott- great project (mind blown)...
just wondering if there was a reason to leave the CurrencyExchange project (gRPC) on version `netcoreapp3.0`?

**Comment by scottaddie** [comment]
Fixed in https://github.com/scottaddie/ContosoLending/commit/93198ba073fefe5b1d9773d2e3b8d3720ea04014. Thank you for the reminder. I simply forgot to do this.
